id: PD4513D5D
initial_creation_type: input
source_metadata:
  Title: Bauddhadharme tathā purāṇeṣu karuṇā
  Editor: Phra Suntharnadhammathada
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  Bauddhadharme tathā purāṇeṣu karuṇā:
    Text Version: Romanized
    Input Personnel: Milan Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:16:42.778048'
last_modified_at: '2022-03-08T17:16:42.778056'
